### ISSUE TITLE
Szar bugos

### ISSUE THREAD

**Issue by szaffo** [ZodX/Pushtest#1]
töröld légyszíves

**Comment by Kelileis** [comment]
The problem also appears on my computer.

**Comment by ZodX** [comment]
Thank you for reporting this problem to me! I'll try to fix the problem asap.

**Comment by ZodX** [comment]
Well guys, it's not a bug at all. I set up the code the way that if you fail the `README`
 test you get a bunch of bugs in the code which are irreversible since it burns into your being.
